### ISSUE TITLE
Field to enter in HomeAssistant - configuration not appointed in github installation text (readme.md)

### ISSUE THREAD

**Issue by agvdberg** [JohNan/home-assistant-flichub#13]
The steps needed to install this very nice integration are described in the readme.md.
The window which fields to fill are not mentioned:
 - Name   (can it be any name or is it sort of login?)
 - IP-address  (already filled with the IP of the FlicHub)
 - Port  (search and found it in the tcpserver.js-script, aka 8123)

It looks like i figured it out by myself.
But it is not working yet at my place so i want to rule out some bad configuration.

**Comment by JohNan** [comment]
You are right, this should be improved. I'll have a look at it.

Name is simply the name you wish the FlicHub device to have.
IP should be the one that is filled automatically
Port should be 8124 by default. You can find it here: https://github.com/JohNan/pyflichub-tcpclient/blob/main/tcpserver.js#L9

**Comment by JohNan** [comment]
Updated the texts to the config fields.
