### ISSUE TITLE
Not able to connect to the Flic Hub LR

### ISSUE THREAD

**Issue by PMPoulsen** [JohNan/home-assistant-flichub#22]
Hi,

I was trying to connect to my Flic Hub LR but un successful, I am getting this error (from logs):

Logger: custom_components.flichub
Source: custom_components/flichub/config_flow.py:131
Integration: Flic Hub ([documentation](https://github.com/JohNan/home-assistant-flichub), [issues](https://github.com/JohNan/home-assistant-flichub/issues))
First occurred: 10.44.04 (1 occurrences)
Last logged: 10.44.04

Error connecting
Traceback (most recent call last):
  File "/config/custom_components/flichub/config_flow.py", line 132, in _test_credentials
    await client_ready.wait()
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/flichub/config_flow.py", line 131, in _test_credentials
    with async_timeout.timeout(CLIENT_READY_TIMEOUT):
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 128, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

I am able to connect to the hub from my phone (app) and have anabled the SDK access in the hup.

Any ideas?

**Comment by JohNan** [comment]
Have you added the script on the hub described here: https://github.com/JohNan/pyflichub-tcpclient

**Comment by PMPoulsen** [comment]
Thanks, I did miss that part, now working like a charm.

Any chance flic twist can be fully support with the rotary dial?

**Comment by JohNan** [comment]
Good to hear that it work now!

I don't own a FlicTwist so it makes it difficult for me to integrate. I have no idea what events and what payload it triggers in the Hub SDK. 🙁

**Comment by PMPoulsen** [comment]
OK thanks, hope you get one soon 😊

**Comment by MostHated** [comment]
Unfortunately, I don't think anyone knows what those events are. They have not exposed them anywhere in the SDK, or updated their repos to include them, even though the thing has been in the works for 2 years. As of now, the thing is just a much more expensive button.
