### ISSUE TITLE
After bluetooth crash in HA - no buttons found anymore

### ISSUE THREAD

**Issue by CannyDuck** [JohNan/home-assistant-flichub#25]
I have a Home Assistant yellow and successful used the your flic integration in past. After I update HA my bluetooth device didn't worked anymore, so I can't used my flic buttons. So I removed the configuration of the Flic integration, but know I can configure the flic hub, but no buttons are found anymore. My bluetooth device is working again. Attached you will find my HA log.
[error_log-7.txt](https://github.com/JohNan/home-assistant-flichub/files/15135101/error_log-7.txt)

**Comment by nicolinuxfr** [comment]
Same error probably as #26

**Comment by arormoser** [comment]
Any news about this issue? I'm having the same problem

**Comment by arormoser** [comment]
I replace this integration with a python script running on a local server in my home, in case anyone need it
[flichub.py.txt](https://github.com/JohNan/home-assistant-flichub/files/15255616/flichub.py.txt)

**Comment by JohNan** [comment]
Sorry for the delay. An update should be available in just a few minutes.
